### ISSUE TITLE
Find out a cause of 'Possible EventEmitter memory leak detected' warning

### ISSUE THREAD

**Issue by KimTaehee** [TaeKyuHyeon/discord-relay#8]
재현:
app 종료시 아래와 같은 메시지 발생

```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [File]. Use emitter.setMaxListeners() to increase limit
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
```

<details>
<summary>전체 로그</summary>

```
AdminController init start
Discord Bot init start
Server init start
{"message":"[    at Object.<anonymous> (/app/app.js:18:8] Application Start","level":"info"}
{"message":"[modules/discord/discord-bot.js:29:14] discord login with token: NzE1MjA4ODgzMTM1ODQwMzY4.XtNIFw.LkzJ7zucyfR5zoKXsSpZSoEzl90","level":"info"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [File]. Use emitter.setMaxListeners() to increase limit
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 finish listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
{"message":"[    at process.<anonymous> (/app/app.js:61:10] unhandeled rejection occured, TypeError: logger.on is not a function","level":"error"}
{"message":"[    at finalize (/app/app.js:32:10] Finalize start","level":"info"}
{"message":"[    at finalize (/app/app.js:39:10] logger flush start.","level":"info"}
```
</details>

**Comment by tkbro** [comment]
#13 
https://github.com/winstonjs/winston/issues/1334
위 이슈 토의 내용에 transform 을 재사용하지 말라는 코드를 보고 수정하였습니다.
추가 확인은 필요할 듯 해보입니다.
